### ISSUE TITLE
Error when trying to use selfContained optional transform

### ISSUE THREAD

**Issue by qubyte** [6to5/6to5ify#31]
I'm attempting to use experimental features (specifically async-await) without explicitly importing the regenerator runtime. Using 6to5ify v3.1.2 and going by the 6to5 docs, I expect the following to do the job:

```javascript
var b = browserify(options)
        .transform(to5ify.configure({
            experimental: true,
            optional: ['selfContained']
        }))
        .require(devPath, {entry: true});
```

However, 6to5ify throws a wobbly about the transformer:

```
ReferenceError: unknown transformer selfContained specified in optional while parsing file: /Users/marke/some-project/frontend/scripts/main.js
    at Function.transform._ensureTransformerNames (/Users/marke/some-project/node_modules/6to5ify/node_modules/6to5-core/lib/6to5/transformation/transform.js:28:13)
    at Function.File.normaliseOptions (/Users/marke/some-project/node_modules/6to5ify/node_modules/6to5-core/lib/6to5/file.js:125:13)
    at new File (/Users/marke/some-project/node_modules/6to5ify/node_modules/6to5-core/lib/6to5/file.js:17:32)
    at Object.transform (/Users/marke/some-project/node_modules/6to5ify/node_modules/6to5-core/lib/6to5/transformation/transform.js:11:14)
    at Stream.end (/Users/marke/some-project/node_modules/6to5ify/index.js:39:23)
    at _end (/Users/marke/some-project/node_modules/6to5ify/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/marke/some-project/node_modules/6to5ify/node_modules/through/index.js:74:5)
    at Transform.onend (/Users/marke/some-project/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:180:16)
    at Transform.emit (events.js:117:20)
```

**Comment by sebmck** [comment]
You'll have to upgrade to 6to5ify 4.0.0 which includes 6to5 3.0.0 which has the `selfContained` transformer.

**Comment by qubyte** [comment]
Oh, sorry. Made an invalid assumption about versions there. As always, thanks for the rapid response!

**Comment by sebmck** [comment]
No problem! 6to5ify is the only plugin that has a version greater than 6to5, all the other plugin majors are on par. I had to bump the major version of 6to5ify pretty early on because I broke the API which makes things a pain.

**Comment by craigdallimore** [comment]
I've found that using the `regeneratorRuntime` with `babelify` is now achieved like so:
```
var b = browserify(options)
        .transform(babelify.configure({
            optional: ['runtime']
        }))
```
note: you will need `babel-runtime` for this.

**Comment by sebmck** [comment]
@craigdallimore Yeah, I recently renamed the `selfContained` transformer to the more descriptive `runtime`. You can find out more via the [docs](http://babeljs.io/docs/usage/runtime/).
